import type { CompanyCardProps } from "./CvModels"

export const CareerProps: CompanyCardProps[] = [
	{
		id: 1,
		companyName: "Kuehne+Nagel",
		logoUrl: "kn.png",
		jobTitle: "Software Developer",
		description: [
			"Developed and maintained frontend features for a large-scale monolith project in the seafreight domain, collaborating with 20 teams.",
			"Utilized Angular with TypeScript and NgRx for state management, leveraging Redux DevTools for efficient debugging.",
			"Wrote unit tests using Jest to ensure code quality and reliability.",
			"Resolved support tickets by writing Groovy scripts, testing SQL scripts on the database, and addressing SonarQube code quality issues.",
			"Participated in backend spikes using Spring Boot to explore solutions, without direct development.",
			"Contributed to Agile workflows with two-week sprints, using Bitbucket for version control, Jira for task management, and Jenkins for deployment.",
		],
		technologies: ["Angular", "TypeScript", "NgRx", "Jest", "Spring Boot"],
		tools: [
			"Jira",
			"Bitbucket",
			"Jenkins",
			"Redux DevTools",
			"IntelliJ",
			"SonarQube",
		],
		methodologies: ["Agile"],
		years: "2024 - Present",
	},
	{
		id: 2,
		companyName: "Natixis",
		logoUrl: "natixis.jpeg",
		jobTitle: "Software Developer",
		description: [
			"As a Frontend Developer on the Workplace team at Natixis, I played a pivotal role in developing internal projects that enhanced operational efficiency. My primary focus was a critical onboarding and offboarding platform, built using Angular with a Spring Boot backend. I was in charge of frontend development, crafting intuitive and responsive user interfaces, while occasionally tackling backend tasks to ensure seamless integration.",
			"After one year, I took on leadership responsibilities as the project main developer, guiding a team of up to four developers. I collaborated closely with product owners to gather requirements, developed comprehensive documentation, designed functional architectures, and managed task allocation through Jira. Additionally, I oversaw support tickets, database management, and user permissions, ensuring the platform’s reliability and security. My ability to balance technical excellence with team coordination drove significant improvements in project delivery and stakeholder satisfaction.",
			"Beyond the main project, I maintained Purple Scan, a secondary web application hosted externally on cPanel. I managed all aspects of this project, from keeping the website updated to handling hosting-related tasks, ensuring its stability and accessibility. As Natixis began transitioning to a Scrum Master role, I briefly took on agile leadership responsibilities before departing, leaving a legacy of impactful solutions and effective team collaboration.",
		],
		technologies: [
			"Angular",
			"Typescript",
			"Spring Boot",
			"MySQL",
			"HTML/CSS",
			"JavaScript",
		],
		tools: [
			"Jira",
			"BitBucket",
			"Confluence",
			"VS Code",
			"WebStorm",
			"Intellij",
			"MySQL Workbench",
		],
		methodologies: ["Agile", "Scrum", "Kanban"],
		years: "2021-2024",
	},
	{
		id: 3,
		companyName: "MrWedo",
		logoUrl: "mrwedo.png",
		jobTitle: "Web Developer",
		description: [
			"Sole developer at a small consulting firm with a five-person team, building WordPress websites for up-and-coming companies seeking financing from the Portugal 2020 program, as well as personal and restaurant websites using Elementor.",
			"Managed end-to-end website development, including gathering client requirements, developing sites, and performing light theme personalization to meet client needs.",
			"Created custom icons and images using Photoshop and Illustrator to enhance website visuals.",
			"Optimized websites for search engines using Yoast SEO and tracked performance with Google Analytics to measure implementation success.",
			"Handled website hosting and deployment using cPanel, delivering under tight deadlines while balancing academic, professional, and personal responsibilities as a bachelor’s and master’s student.",
			"Adapted to a fast-paced, ad-hoc environment to deliver tailored solutions with limited resources, developing strong time management and prioritization skills.",
			"Left during COVID-19 to focus on completing master’s degree.",
		],
		technologies: ["WordPress", "Elementor", "HTML/CSS", "JavaScript"],
		tools: [
			"cPanel",
			"Photoshop",
			"Illustrator",
			"Yoast SEO",
			"Google Analytics",
		],
		methodologies: ["Ad-hoc"],
		years: "2019 - 2020",
	},
	{
		id: 4,
		companyName: "Multifundos",
		logoUrl: "multifundos.png",
		jobTitle: "Intern",
		description: [
			"Summer Intern as Wordpress developer. Helped redesign the company website",
		],
		technologies: ["WordPress"],
		tools: ["cPanel", "Photoshop", "Illustrator"],
		methodologies: ["Ad-hoc"],
		years: "2018",
	},
]
